In [3]:
import pandas as pd
import numpy as np

In [4]:
# csv 불러 오기
df = pd.read_csv('/Users/baeminkyung/Desktop/github/UNO_BWMovie_recsys/dataset/signup_movie_list.csv')
df

,Unnamed: 0.1,Unnamed: 0,id,title,revenue,vote_average,imdb_id,original_title,overview,popularity,poster_path,genres,keywords
0,501,501,424,Schindler's List,321365567,8.573,tt0108052,Schindler's List,The true story of how businessman Oskar Schind...,65.084,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,"Drama, History, War","factory, hero, based on novel or book, nazi, c..."
1,424,424,372058,Your Name.,357986087,8.514,tt5311514,君の名は。,High schoolers Mitsuha and Taki are complete s...,68.999,/q719jXXEzOoYaps6babgKnONONX.jpg,"Romance, Animation, Drama","race against time, afterlife, natural disaster..."
2,48,48,155,The Dark Knight,1004558444,8.512,tt0468569,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f..."
3,152,152,13,Forrest Gump,677387716,8.477,tt0109830,Forrest Gump,A man with a low IQ has accomplished great thi...,92.693,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,"Comedy, Drama, Romance","vietnam war, vietnam veteran, mentally disable..."
4,32,32,122,The Lord of the Rings: The Return of the King,1118888979,8.474,tt0167260,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,99.276,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,"Adventure, Fantasy, Action","based on novel or book, orcs, elves, dwarf, br..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,168,168,9806,The Incredibles,631442092,7.704,tt0317705,The Incredibles,Bob Parr has given up his superhero days to lo...,62.609,/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg,"Action, Adventure, Animation, Family","island, hero, secret identity, superhero, wret..."
96,386,386,272,Batman Begins,374218673,7.701,tt0372784,Batman Begins,"Driven by tragedy, billionaire Bruce Wayne ded...",66.286,/4MpN4kIEqUjW8OPtOQJXlTdHiJV.jpg,"Action, Crime, Drama","martial arts, undercover, loss of loved one, s..."
97,63,63,767,Harry Potter and the Half-Blood Prince,933959197,7.697,tt0417741,Harry Potter and the Half-Blood Prince,As Lord Voldemort tightens his grip on both th...,121.735,/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg,"Adventure, Fantasy","witch, dying and death, london, england, magic..."
98,529,529,22881,The Blind Side,309208309,7.692,tt0878804,The Blind Side,"The story of Michael Oher, a homeless and trau...",35.267,/bMgq7VBriuBFknXEe9E9pVBYGZq.jpg,Drama,"sports, american football, adoption, private s..."
99,62,62,675,Harry Potter and the Order of the Phoenix,938212738,7.686,tt0373889,Harry Potter and the Order of the Phoenix,Returning for his fifth year of study at Hogwa...,117.168,/5aOyriWkPec0zUDxmHFP9qMmBaj.jpg,"Adventure, Fantasy","witch, dying and death, court, magic, prophecy..."

In [5]:
# 랜덤으로 25개 뽑고, title, original_title, genres, poster_path 열만 추출, index 번호 새로 부여하기
sampled_df = df.sample(n=25)[['id', 'original_title', 'genres','poster_path']].reset_index(drop=True)
"""포스터 보기 : https://image.tmdb.org/t/p/w500/<이미지 파일명>"""
# display 함수를 사용하여 DataFrame을 표 형태로 출력
from IPython.display import display
display(sampled_df)

,id,original_title,genres,poster_path
0,372058,君の名は。,"Romance, Animation, Drama",/q719jXXEzOoYaps6babgKnONONX.jpg
1,502356,The Super Mario Bros. Movie,"Animation, Family, Adventure, Fantasy, Comedy",/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg
2,424,Schindler's List,"Drama, History, War",/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg
3,9552,The Exorcist,Horror,/4ucLGcXVVSVnsfkGtbLY4XAius8.jpg
4,475557,Joker,"Crime, Thriller, Drama",/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg
5,45269,The King's Speech,"Drama, History",/uQ538BfYLDJh3GXlzRZLo0j7PFj.jpg
6,12,Finding Nemo,"Animation, Family",/ggQ6o8X5984OCh3kZi2UIJQJY5y.jpg
7,597,Titanic,"Drama, Romance",/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg
8,313369,La La Land,"Comedy, Drama, Romance, Music",/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg
9,120,The Lord of the Rings: The Fellowship of the Ring,"Adventure, Fantasy, Action",/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg
10,9806,The Incredibles,"Action, Adventure, Animation, Family",/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg
11,675,Harry Potter and the Order of the Phoenix,"Adventure, Fantasy",/5aOyriWkPec0zUDxmHFP9qMmBaj.jpg
12,98,Gladiator,"Action, Drama, Adventure",/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg
13,14,American Beauty,Drama,/wby9315QzVKdW9BonAefg8jGTTb.jpg
14,155,The Dark Knight,"Drama, Action, Crime, Thriller",/qJ2tW6WMUDux911r6m7haRef0WH.jpg
15,24428,The Avengers,"Science Fiction, Action, Adventure",/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg
16,272,Batman Begins,"Action, Crime, Drama",/4MpN4kIEqUjW8OPtOQJXlTdHiJV.jpg
17,585,"Monsters, Inc.","Animation, Comedy, Family",/sgheSKxZkttIe8ONsf2sWXPgip3.jpg
18,166428,How to Train Your Dragon: The Hidden World,"Animation, Family, Adventure",/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg
19,11,Star Wars,"Adventure, Action, Science Fiction",/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg
20,671,Harry Potter and the Philosopher's Stone,"Adventure, Fantasy",/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg
21,316029,The Greatest Showman,Drama,/b9CeobiihCx1uG1tpw8hXmpi7nm.jpg
22,634649,Spider-Man: No Way Home,"Action, Adventure, Science Fiction",/5weKu49pzJCt06OPpjvT80efnQj.jpg
23,916224,すずめの戸締まり,"Animation, Drama, Adventure, Fantasy",/vIeu8WysZrTSFb2uhPViKjX9EcC.jpg
24,68718,Django Unchained,"Drama, Western",/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg